
name: Upload to Codecov

on:
  push:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
